title: Textract Table Extractor
description: Extract tables from your documents using Amazon Textract
instructions: ''
type: object
documents:
  - selected
properties:
  output_format:
    title: Output format
    type: string
    default: csv
    enum:
      - csv
      - xlsx
  start_page:
    title: Start page 
    type: integer
    description: 'Page number where the table(s) begin'
    default: 1
  end_page:
    title: End page 
    type: integer
    description: 'Page number where the table(s) begin'
    default: 1
categories: 
  - extraction
  - premium
cost:
  price: 10
  amount: 1
  unit: page
version: 2
